CMakeLists.txt

This PR renames BUILD_PYTHON_BINDINGS to XGRAMMAR_BUILD_PYTHON_BINDINGS for integration with other libraries.

[fix] Rename BUILD_PYTHON_BINDINGS to XGRAMMAR_BUILD_PYTHON_BINDINGS

---

cpp/grammar_matcher.cc
cpp/grammar_matcher_preproc.h
cpp/pybind/pybind.cc
cpp/pybind/python_methods.cc
cpp/pybind/python_methods.h
cpp/tokenizer.cc
include/xgrammar/xgrammar.h
python/xgrammar/xgrammar.py
tests/python/test_builtin_grammar_json.py
tests/python/test_builtin_grammar_json_schema.py
tests/python/test_custom_grammar.py
tests/python/test_grammar_matcher.py
tests/python/test_regex_converter.py
tests/python/test_tokenizer_info.py
web/example/src/example.ts
web/src/xgrammar.ts
web/src/xgrammar_binding.cc
web/tests/grammar.test.ts

This PR renames these variables and methods for simplicity:
- `GrammarMatcher.find_next_token_bitmask` -> `GrammarMatcher.get_next_token_bitmask`
- `GrammarMatcher.__init__(stop_token_ids)` -> `GrammarMatcher.__init__(override_stop_tokens)`
- `TokenizerInfo.raw_vocab` -> `TokenizerInfo.decoded_vocab`

[Fix] Rename method and variable names

---

cpp/grammar_matcher_preproc.h
python/xgrammar/xgrammar.py
tests/python/test_builtin_grammar_json.py
tests/python/test_builtin_grammar_json_schema.py
tests/python/test_custom_grammar.py
tests/python/test_grammar_matcher.py

Now in GrammarMatcher, if we pass a huggingface tokenizer, it will be converted into xgrammar TokenizerInfo first. This process could be slow. However, if we can construct TokenizerInfo first and then construct the GrammarMatcher, the construction of GrammarMatcher would be much faster.
This PR enforces user to construct a TokenizerInfo object first then pass it into GrammarMatcher, instead passing raw huggingface tokenizer to it, avoiding the redundant processing.
This PR also adds `<|eos|>` as an EOS token.

[Fix] Avoid directly passing tokenizer to GrammarMatcher

---

.github/workflows/wheel_mac.yaml
.github/workflows/wheel_manylinux.yaml
.github/workflows/wheel_windows.yaml
scripts/build_xgrammar_wheel_manylinux.sh

PyBind is Python-version-depended. Previously we only build XGrammar once (where PyBind is built only once as well) and then build the wheel for each Python version, which causes Python version error.
This PR updates the build scripts to build XGrammar once for each Python version.

[Package] Build once for each Python version

---

cpp/compiler.cc
cpp/pybind/pybind.cc
python/xgrammar/compiler.py
python/xgrammar/testing.py
tests/python/test_custom_grammar.py
tests/python/test_grammar_compiler.py
tests/python/test_regex_converter.py

This PR renames compile_bnf_grammar to compile_grammar to reflect the latest API changes.

[Refactor] Rename compile_bnf_grammar to compile_grammar

---

docs/start/quick_start.rst
examples/hf_transformers/transformers_example.py
python/xgrammar/apply_token_bitmask_cpu.py
python/xgrammar/contrib/hf.py
python/xgrammar/matcher.py

This PR uses the `transformers_example.py` as Quick Start example in the doc. Tried on both CUDA and Mac (with `device="cpu"`). Also change `pin_memory=torch.cuda.is_available(),` for `allocate_token_bitmask()` since it is not supported for all devices (e.g. Mac).

[HF] Change quick start example to HF, make it run on both CUDA and Mac

---

cpp/compiler.cc
python/xgrammar/apply_token_bitmask_cpu.py
tests/python/test_grammar_compiler.py

This PR bypasses using `ThreadPool` or `std::mutex` when `max_threads=1` when compiling grammar. This is motivated by how WebAssembly does not have good support for multithreading.
Unrelated to this, fix a bug in CPU bitmasking.
Tested with `pytest tests/`.

[Compiler] Special case max_thread=1 to not use ThreadPool or mutex

---

cpp/pybind/CMakeLists.txt
cpp/pybind/python_methods.cc
cpp/pybind/python_methods.h
python/xgrammar/matcher.py
python/xgrammar/testing.py

This PR removes the dependency of libtorch in C++. It will pass data_ptr to C++ instead of torch::Tensor.

[Refactor] Remove libtorch dependency

---

cmake/config.cmake

This PR removes useless config info in config.cmake.

[Fix] Update config.cmake

---

python/setup.py
python/xgrammar/version.py
scripts/sync_package.py

This PR fixes the problem in local installation of python package. It fixes the wrong path of `version.py` in `setup.py`.
Co-authored-by: zanderjiang <zander.jiang@gmail.com>

[Fix] Fix local Python package installation

---

cpp/json_schema_converter.cc
tests/python/test_json_schema_converter.py

This PR introduces simple regex pattern support + integer ranges.

Simple pattern support + integer ranges

---

cpp/json_schema_converter.cc
tests/python/test_json_schema_converter.py

This PR updates the changes in #106. It removes the try-catch block, and make GenerateRangeRegex a static member function.

[Fix] Fix format and usage issues in schema converter

---

cpp/support/thread_safe_cache.h
tests/cpp/test_parallel.cc

1. Add a cpp test on cache efficiency and correctness
2. Refactor the thread_safe_cache.
In the new thread_safe_cache, we maintain only 1 unified mapping instead of 2. In addition, in our implementation, we acquire the unique_lock less, which may bring a significant improvement in efficiency in some cases.
Here's the result for  `TEST(XGrammarParallelTest, CacheEfficiency)` on my machine `AMD EPYC 7R32`.
End to end time (preprocessing time `2s` not included):
- Old cache: `1152ms`
- New cache: `217ms`
gcc version: `13.2.0`

[Performance] Rewrite the thread_safe cache.

---

cpp/grammar_parser.cc
tests/python/test_grammar_parser.py

Current `grammar_parser.cc` can't handle inline comment correctly:
```gbnf
root ::= a # inline comment
a ::= "a"
```
Raise following error:
```
EBNF parse error at line 2, column 3: Expect element
```
Fixed by preventing inline comments from consuming line breaks.
P.S. How about integrating `llama.cpp`'s GBNF parsing implementation? Current implementation doesn't seems to be robust enough.

[Fix] Add support for GBNF inline comment

---

cpp/ebnf_script_creator.cc
cpp/ebnf_script_creator.h
cpp/json_schema_converter.cc
include/xgrammar/compiler.h
include/xgrammar/object.h

This PR adds a class EBNFScriptCreator to handle construction of ebnf in converters from other structures to ebnf, with auto renaming.

[Refactor] Introduce EBNFScriptCreator

---

cpp/json_schema_converter.cc
python/xgrammar/compiler.py
tests/python/test_json_schema_converter.py

This PR enhances the JSONSchemaConverter:
- Support `oneOf`
- Support `allOf` with one option
- Support `$ref` with any path (previously only those starting with `#/$def/` is supported)
- Support object with `properties` specified but not `type`, and array with `item` specified but not `type`
This PR also completes support for pydantic V1.

[Feature] Enhance JSON Schema Converter

---

cpp/compiled_grammar_data_structure.h
cpp/compiler.cc
cpp/grammar_matcher.cc
cpp/grammar_matcher_base.cc
cpp/grammar_matcher_base.h
cpp/grammar_matcher_data_structure.h

This PR renames:
- RuleExpr->StackElement
- GrammarMatcherForCompiler->GrammarMatcherForTokenMaskCache
for better structure.

[Refactor] Rename internal classes for better structure

---

cpp/compiled_grammar_data_structure.h
cpp/grammar.cc
cpp/grammar_builder.h
cpp/grammar_data_structure.h
cpp/grammar_functor.cc
cpp/grammar_functor.h
cpp/grammar_matcher.cc
cpp/grammar_matcher_base.cc
cpp/grammar_matcher_base.h
cpp/grammar_parser.cc
cpp/grammar_parser.h
cpp/grammar_serializer.cc
cpp/grammar_serializer.h
cpp/persistent_stack.h
tests/python/test_grammar_parser.py

This PR supports TagDispatch. Its grammar is:
```
rule ::= TagDispatch(("tag1", rule1), ("tag2", rule2), ...)
```
And its semantic is: allowing any input at start. When input matches tag1, let the following input match rule1 until rule1 finishes. The same for rule1 and tag2. When the rule finished, get to start, allow any input, and check tag again. 
Its backend is not supported yet.

[FunctionCalling] Support TagDispatch

---

CMakeLists.txt
cpp/grammar_functor.cc

This PR fixes the problem in #149 about the hidden overloaded function `Apply`. This will cause a compilation error.

[Fix] Fix compilation error with virtual overloaded function

---

3rdparty/picojson/picojson.h

This PR adds a guard to avoid the macro redifinition of `__STDC_FORMAT_MACROS` in 3rdparty picojson.

[3rdparty] Avoid macro redefinition in picojson

---

cpp/grammar_matcher.cc
tests/python/test_grammar_matcher.py

In `GrammarMatcher::Impl::Rollback` (1), the number of chars to rollback for each token is determined by the `token_length_history` record.
However, `GrammarMatcher::Impl::AcceptStopToken` (2) does not push an amount into this history. This causes a straightforward bug where the wrong number of states are reverted when rolling back after the stop token is accepted.
I fixed the bug by appending "1" to the token length history for the stop token, since it also pushes a single `{}` stack element.
The `test_termination` does not catch this issue: it does in fact rollback too many characters, but the rolled back sequence is still an acceptable one because it removes _all of_ the second key/value pair text. By updating the test to separate this K/V into two tokens, if the value is rolled back …

[Fix] Fix broken rollback char count after accepting stop token

---

cpp/grammar_matcher.cc
cpp/pybind/python_methods.cc
cpp/pybind/python_methods.h
cpp/support/dynamic_bitset.h
include/xgrammar/matcher.h
python/xgrammar/matcher.py
tests/python/test_grammar_matcher_json.py
tests/python/test_grammar_matcher_tag_dispatch.py

Sometimes the bitmask is all-true, which means the mask don't need to be applied. This is especially common for function calling cases because we only constrain the part within the tag, and for the part out of tag, all tokens are allowed.
This PR introduces a bool return value for `FillNextTokenBitmask` to represent if the filled bitmask need to applied. If false, user can skip applying the bitmask.
This PR also updates the logic for TagDispatch, so that when the stack top is at an tag dispatch rule (corresponding to the part out of tag), the special tokens are allowed.

[Feature] Optional Token Bitmask

---

cpp/grammar_matcher.cc
tests/python/test_grammar_matcher.py

In `GrammarMatcher::Impl::AcceptToken`, if a char is not accepted, the matcher state is left broken because the partially-advanced token state remains in the matcher.
The below function, `GrammarMatcher::Impl::_DebugAcceptString`, handles this case correctly. I'm not sure why it isn't present in AcceptToken.
If this behaviour is not deliberate, please accept this fix so that AcceptToken can handle rejections gracefully.

[Fix] Rollback safely when token acceptance fails

---

cpp/fsm.h

When compiling with `gcc-13.2.0`, we encountered a false-positive "dangling-reference" warning.
To mitigate this issue, we now construct the object outside the inner loop to prevent the false positive.
For more details on this gcc bug, refer to [this article](https://trofi.github.io/posts/264-gcc-s-new-Wdangling-reference-warning.html).

fix(fsm): fix error of dangling-reference in gcc-13

---

tests/cpp/test_thread_safe_cache.cc

This PR aims to fix #168 
The `unordered_map` in `LifeSpanHook` is not thread safe, so we need to protect it with a lock.

fix(test): fix the concurrency issue in #168 

---

cpp/grammar_matcher_base.cc
cpp/grammar_parser.cc
cpp/regex_converter.cc
cpp/support/cpptrace.h
cpp/support/logging.h
tests/python/test_regex_converter.py

This PR fixes these issues in regex converter:
- Adds validation for empty character classes [] which are now properly rejected
- Implements support for non-capturing groups (?:...) and named capturing groups (?<name>...)
- Adds proper error handling for unmatched parentheses
- Implements support for empty alternatives in groups like (a|)
- Adds validation for unsupported regex features with clear error messages:
- Lookaheads ((?=...), (?!...))
- Lookbehinds ((?<=...), (?<!...))
- Inline modifiers ((?i))

[Fix] Fix regex converter

---

cpp/grammar.cc
cpp/grammar_parser.cc
cpp/regex_converter.cc
include/xgrammar/grammar.h
python/xgrammar/grammar.py
tests/python/test_grammar_matcher_regex.py
tests/python/test_grammar_parser.py
tests/python/test_regex_converter.py

This PR supports the empty parentheses `()` and non-greedy modifier `?` in regex. It also forbids consecutive quantifiers (e.g. `++`, `{1,2}{1,2}`) in the regex and EBNF.
It also provides a `print_converted_ebnf` parameter for `Grammar.from_regex`, helping debugging.

[Fix] Fix problems in regex converter

---

tests/python/test_grammar_matcher_regex.py

There is an issue with the compiler and lazy character classes.
The test I have added will raise the following exception:
`RuntimeError: [12:25:32] /workspace/cpp/grammar_parser.cc:78: EBNF parse error at line 1, column 16: Expect element`

test lazy character class

---

.pre-commit-config.yaml

This PR avoids sorting the toml file.

[Maintain] Add no-sort to toml fmt

---

scripts/build_xgrammar_wheel_manylinux.sh

This PR supports Python 3.13 for linux wheels. Other platforms are upcoming.

[Maintain] Support Python 3.13 for Manylinux

---

cpp/grammar_matcher_base.cc

I encountered "-Werror=maybe-uninitialized" when compiling the latest version of xgrammar in TensorRT-LLM. The warning can be resolved by explicitly checking if `root_tag_dispatch_fsm` is initialized.
In xgrammar's CMake file, setting `-flto=auto` can also prevent this warning. 
Do you mind merging this PR? @Ubospica

Fix potential maybe-uninitialized warning

---

python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.cu
python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.py

This PR enhances the compatibility of apply_token_bitmask_inplace_cuda, introduced in #186, for cuda<12.4, >12, torch > 1.10. It solves the compilation error in SGLang CI.
It also renames the vars in `python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.cu` to the naming convention of xgrammar.

[Fix] Fix compatibility for apply_token_bitmask_inplace

---

README.md

Modular MAX 25.1 shipped this month, which uses XGrammar for structured output. 
https://docs.modular.com/max/serve/structured-output

Update README to announce that Modular MAX uses XGrammar

---

cpp/grammar_matcher.cc
cpp/support/dynamic_bitset.h
python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.cu
python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.py
python/xgrammar/kernels/apply_token_bitmask_inplace_triton.py
python/xgrammar/matcher.py
python/xgrammar/testing.py
tests/python/test_token_bitmask_operations.py

This PR supports:
1. Padding on the vocabulary dimension for logits. vLLM could introduce such padding and this is not supported by the previous kernel.
2. Unequal batch size for logits and bitmask when indices are specified. When indices are not specified, we require the batch sizes for logits and bitmask the same. When indices are specified, we only require the indices larger than

[Feature] Support padding for logits and unequal batch size for logits and bitmask

---

cpp/grammar_compiler.cc
cpp/grammar_functor.cc
cpp/structural_tag.cc
include/xgrammar/grammar.h
python/xgrammar/compiler.py
python/xgrammar/grammar.py
tests/python/test_grammar_matcher_structural_tag.py

This PR renames the field "start" to "begin" in StructuralTagItem. The name "begin" better aligns with the naming convention in python.

[Refactor][Breaking] Rename start->begin in StructuralTag

---

python/xgrammar/grammar.py
python/xgrammar/testing.py
tests/python/test_grammar_union_concat.py

This PR provides Grammar.union to combine several grammars into one. The combined grammar can accept strings that follow any of the prior grammars.

[Feature] Expose Grammar.union

---

cpp/grammar.cc
cpp/grammar_compiler.cc
cpp/grammar_functor.cc
cpp/grammar_functor.h
cpp/grammar_matcher.cc
cpp/grammar_matcher_base.h
cpp/grammar_parser.cc
cpp/grammar_parser.h
cpp/json_schema_converter.cc
cpp/regex_converter.cc
cpp/structural_tag.cc
cpp/support/encoding.h
cpp/support/logging.h
cpp/support/thread_pool.h
include/xgrammar/grammar.h
include/xgrammar/object.h

Currently, there are many headers in C++ files that are not used directly. We remove all of them (thanks to clangd).
Moreover, it seems that an `inline` is missing in `cpp/support/thread_pool.h`, which may lead to a potential violation of ODR in the future.
Maybe this PR should be merged only after a C++ test ci is ready to ensure correctness.

[Style] Remove unused headers

---

python/xgrammar/kernels/__init__.py
python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.py
python/xgrammar/matcher.py

The CUDA driver might be available but the full CUDA toolkit, ninja, and gcc/clang might not be installed so we won't have enough tools to compile the kernel, and in this case use triton as a fallback. 
We could consider doing an AOT of the kernel and not JITing the kernel extension, however this really blows the packaging complexity out of the water since we would have to target multiple PyTorch extension ABIs.

Fallback to triton if we fail to compile for CUDA

---

pyproject.toml

Activate editable install settings to improve the development experience by allowing rebuilds and verbose output during installation.

Enable editable installation

---

cpp/grammar_matcher.cc

- Modify the device type check to allow kDLCUDAHost in addition to kDLCPU.
- This change ensures that token bitmasks can be stored in pinned memory (kDLCUDAHost).

[Fix] Add support for kDLCUDAHost in token bitmask device type check

---

cpp/grammar.cc
cpp/json_schema_converter.cc
cpp/nanobind/nanobind.cc
include/xgrammar/grammar.h
python/xgrammar/grammar.py
tests/python/test_json_schema_converter.py

This PR solves the "root rule not found" issue for primitives in json schema converter.

[Fix] Fix primitives for json schema converter

---

CMakeLists.txt

This switches the optimization level from -Ofast to -O3. 
The motivation is that `-Ofast` causes a change in the global floating point behaviour in python.
Currently we see the following surprising behavior, where the if statement changes from False to True after importing xgrammar. 
```python
smallest_subnormal_double = 2.0 ** (-1074)
print("equal" if smallest_subnormal_double == 0.0 else "not equal") # prints non-equal
import xgrammar
print("equal" if smallest_subnormal_double == 0.0 else "not equal") # prints equal
```
(Python 3.12.7, linux, x86-64, xgrammar==0.1.11)
Note, I get this issue with version `0.1.11`, but not with `0.1.16`. 
I don't understand why to be honest, but I expect the underlying issue to be present with `-Ofast`
There's a blog post with more information here: …

[Fix] Switch release compilation flag from -Ofast to -O3

---

pyproject.toml
python/xgrammar/contrib/mlxlm.py

After a chat with @Ubospica , I am filing this PR to fix https://github.com/mlc-ai/xgrammar/issues/270
This module provides a logit processor for mlx_lm, just like hf.py provides one for Hugging Face Transformers.
This module is runnable and works demonstrating that XGrammar runs on Apple Silicon via MLX and mlx-lm, just like it works on CUDA via PyTorch and Hugging Face Transformers.
You can run this module like the following
```shell
python -m mlxlm \
--model mlx-community/Qwen2.5-Coder-3B-Instruct-4bit \
--prompt "Generate a very simple example JSON. No text. Only the JSON."
```
It generates a grammar-verified JSON like the following:
```json
{
"name": "John Doe",
"age": 30,
"city": "New York"
}
```
This pull request adds mlx-lm as an optional dependency `apple-silicon`. To run this …

Add module xgrammar.contrib.mlxlm

---

.github/workflows/documentation.yaml
tests/cpp/test_thread_pool.cc
tests/cpp/test_thread_safe_cache.cc

This PR disables slow C++ test cases. These tests should ideally disable in a configurable manner. cc @DarkSharpness

Disable slow C++ test cases

---

python/xgrammar/contrib/hf.py

My use case is that I need to follow a different grammar for each row in a batch. I couldn't find a way to do this natively with current API, so started hacking and came up with the changes in the PR. I'm not sure about the broader context, so would appreciate a comment if this approach indeed makes sense. 
```
class CountryPoland(ClassSchema):
country: Literal["Poland"]
class CountryGermany(ClassSchema):
country: Literal["Germany"]
tokenizer_info = xgr.TokenizerInfo.from_huggingface(tokenizer, vocab_size=config.vocab_size)
grammar_compiler = xgr.GrammarCompiler(tokenizer_info)
compiled_grammars = [
grammar_compiler.compile_json_schema(CountryPoland),
grammar_compiler.compile_json_schema(CountryGermany),
]
logit_processor = LogitsProcessor(compiled_grammars)
logit_processor = …
```

HuggingFace `LogitsProcessor` to accept also list of compiled grammars

---

.github/workflows/unit_test.yaml
pyproject.toml
python/xgrammar/contrib/mlxlm.py
python/xgrammar/kernels/__init__.py
python/xgrammar/kernels/apply_token_bitmask_mlx.py
tests/python/test_token_bitmask_operations.py

As described in https://github.com/mlc-ai/xgrammar/pull/285#issue-2961934829, there are four ways to implement apply_token_bitmask for Apple Silicon in MLX. This PR is approach 4, which is from Angelos Katharopoulos. Kudos to Angelos!
Also, as described in https://github.com/mlc-ai/xgrammar/pull/285#issuecomment-2768166617, this approach is the simplest and the most performant option.  After the merge of this PR, I will close the rest PRs implementing other approaches:
- https://github.com/mlc-ai/xgrammar/pull/283
- https://github.com/mlc-ai/xgrammar/pull/285
For our reference, I am highlighting the experiment report at https://github.com/mlc-ai/xgrammar/pull/285#issuecomment-2768166617 with content copied to the following:
- Manually written Metal GPU kernel compiled with …

Add MLX kernel to support Apple Silicon

---

cpp/support/encoding.cc
cpp/support/encoding.h

It's a minor bug. When handling escape characters, it can't handle `\?` correctly at present. This PR fixed the problem.

[fix]fix the handling for '\?'.

---

python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.py

This PR fixes an error when compiling the cpp extension on Windows caused by -Wno-switch-bool, which is not available on MSVC.

Fix torch extension build cflags on Windows

---

cpp/grammar_matcher.cc
cpp/nanobind/nanobind.cc
include/xgrammar/matcher.h
python/xgrammar/matcher.py
python/xgrammar/testing.py
tests/python/test_grammar_compiler.py
tests/python/test_grammar_matcher_basic.py
tests/python/test_grammar_matcher_ebnf.py
tests/python/test_grammar_matcher_json.py
tests/python/test_grammar_matcher_json_schema.py
tests/python/test_grammar_matcher_regex.py
tests/python/test_grammar_matcher_structural_tag.py
tests/python/test_regex_converter.py

This PR exposes two internal functions of the GrammarMatcher:
1. accept_string: directly accept a string or byte sequence
2. _debug_print_internal_states: print the internal state for debugging
It also refines the logging info of GrammarMatcher.accept_token and GrammarMatcher.accept_string.
It also change the behavior of accept_token to return False when the token is out of boundary or special token. Previously it will throw RuntimeError.

Expose accept_string and print_internal_states

---

cpp/grammar_matcher_base.cc
cpp/grammar_matcher_base.h
cpp/nanobind/nanobind.cc
cpp/support/recursion_guard.cc
cpp/support/recursion_guard.h
python/xgrammar/__init__.py
python/xgrammar/config.py
python/xgrammar/matcher.py
tests/python/test_recursion_depth.py

This PR provides a new set of methods to control the max recursion depth:
- set_max_recursion_depth
- get_max_recursion_depth
- max_recursion_depth, a decorator
This avoids the segfault problem of xgrammar. Instead, an RuntimeError will be thrown.

feat: Set and get max_recursion_depth

---

pyproject.toml
python/xgrammar/tokenizer_info.py

Sentencepiece has not had a new release in over a year, and users are running into easily fixable install issues like CMake minimum versions, missing headers, and missing wheels for newer python versions. See recent issues: https://github.com/google/sentencepiece/issues, like this one for example: https://github.com/google/sentencepiece/issues/1113
Tiktoken hasn't caused any particular issues, but I'm including it because it's used in the same capacity here.
Both dependencies are only actually used if users are, so it seems pointless to depend on them directly. This updates the support to silently skip over them if they are not installed.

Make sentencepiece and tiktoken optional deps

---

cpp/fsm.cc
cpp/fsm.h
cpp/fsm_builder.cc
cpp/json_schema_converter.cc
cpp/support/compact_2d_array.h
cpp/support/utils.h

When returning with OK, we don't need to actually specify the type in most cases. So we implement a wrapper class `PartialResult` to enable users to write code like: `ResultOK` and `ResultErr`. Still, we have fallback to specify the result type or the error type, and the code will look like `ResultOK<T>` and `ResultErr<E>`

[Minor] Replace all Result<...>::Ok with ResultOk

---

cpp/json_schema_converter.cc

When compiled with `CMAKE_BUILD_TYPE Debug`, we found that some of the tests crashed.
Try this in main branch and it will lead to some crashs:
```
pytest -k test_empty_
```
I would suggest turning on `XGRAMMAR_DCHECK` in ci to detect more bugs like this.
One more suggestion. I don't think magic numbers like `-1` is good enough. Maybe we can rewrite with `std::optional<int>` for better readability in future.

Fix: fix wrong DEBUG boundary check

---

cpp/earley_parser.cc
cpp/fsm.h
cpp/grammar_matcher.cc

Like #369, this PR fixes wrong boundary check in earley parser. Moreover, it supports fsms in a more general way.
This PR also fixed some latent issues:
- Support epsilon edges in fsms.
- Disable right recursion optimization on fsms.
- Fix the boundary check. 
- Fix the parser when a fsm is referred by other rules.

[Fix]fix behaviors and boundary check in earley parser.

---

cpp/earley_parser.cc
cpp/earley_parser.h
cpp/grammar_builder.h
cpp/grammar_compiler.cc
cpp/grammar_functor.cc
cpp/grammar_functor.h
cpp/grammar_impl.h
cpp/grammar_matcher.cc
cpp/grammar_parser.cc
cpp/grammar_printer.cc
cpp/grammar_printer.h
tests/python/test_grammar_matcher_ebnf.py
tests/python/test_grammar_matcher_regex.py
tests/python/test_grammar_parser.py
tests/python/test_serialization.py

Currently, if we try to compile a grammar with a expression like `[a-z]{2, 20000}`, it will cost a lot of time to compile the grammar. In this PR, we add a new type of expression `kRepeat` in the parser, which can significantly improve the efficiency in such cases.

[Feature] Add a new expression to represent repetition to speed up.

---

cpp/grammar_compiler.cc
tests/python/test_grammar_matcher_json_schema.py

This PR fixes a minor bug in Grammar Compiler, which is reported by #382. The bug is led by a small optimization, which is used to reduce the time to fill the `tmp_rejected_indices`. In the implementation, jf `tmp_rejected_indices == false`, then it shouldn't be set to `true` again, since some infomation will miss. Regretfully,  when `tmp_rejected_indices` is initialized with `false`, and the `tmp_rejected_indices` is set to `true` until the end of the function, then the incorrect `tmp_rejected_indices` will be passed.
Signed-off-by: Yuchuan <blemiade_qinchuan@sjtu.edu.cn>

[Fix]Fix the grammar_compiler.

---

cpp/compiled_grammar.cc

This PR fixes the print function of adaptivetokenmask when its type is `kDynamicBitset`. This is helpful for development.
Signed-off-by: Yuchuan <blemiade_qinchuan@sjtu.edu.cn>

[Fix] Fix the print function of AdaptiveTokenMask.

---

cpp/regex_converter.cc
tests/python/test_grammar_matcher_json_schema.py
tests/python/test_regex_converter.py

Currently, when we enconter such schema:
```
{
"type": "object",
"properties": {
"_links": {
"type": "object",
"patternProperties": {
"": {
"type": "object",
"properties": {
"href": {
"type": "string"
}
}
}
}
}
}
}
```
This will lead to a segmentation fault. It is caused by the lack of handling with the empty regex when `RegexConverter` is constructed. This PR fixed it.
Signed-off-by: Yuchuan <blemiade_qinchuan@sjtu.edu.cn>

[Fix] Fix regex converter when the property's pattern is empty.

---

cpp/json_schema_converter.cc
cpp/json_schema_converter.h
cpp/nanobind/nanobind.cc
cpp/structural_tag.cc
cpp/structural_tag.h
cpp/testing.cc
cpp/testing.h
docs/api/python/structural_tag.rst
docs/tutorials/structural_tag.md
python/xgrammar/structural_tag.py
tests/python/test_structural_tag_converter.py

This PR is based on #387 and #420. This PR provides a new schema, which allows users to constrain the output with Qwen's xml-style function callings' parameters. For example:
```
xml_style = {
"type": "qwen_xml_parameter",
"json_schema": {
"type": "object",
"properties": {"name": {"type": "string"}, "age": {"type": "integer"}},
"required": ["name", "age"],
},
},
structural_tag = {"type": "structural_tag", "format": xml_style}
stag_ebnf = xgr.Grammar.from_structural_tag(structural_tag)
```
Then, we can use `stag_ebnf` to constrain the outputs. For example, `"<parameter=name>Bob</parameter><parameter=age>\t100\n</parameter>` is a valid output.

[Feature] Enhance structural tags by providing xml-style tags.

---

python/xgrammar/grammar.py
tests/python/test_structural_tag_converter.py

This PR fixes the behavior of `from_structural_tag` method when the parameter is a `StructuralTag`.

[Fix] Fix from_structural_tag when the parameter is a StructuralTag.

---

python/xgrammar/testing.py
tests/python/test_token_bitmask_operations.py

This PR provides a function to convert a  bitmask to bool mask, the API is:
```
def _bitmask_to_bool_mask(bit_mask: torch.Tensor, vocab_size: Optional[int] = None) -> torch.Tensor:
```

[Feature] Add a function to convert bitmasks to bool masks for development usage.

---

cpp/grammar_compiler.cc

This PR optimized the efficiency of TagDispatch expression. At the initial state, only the tokens contain tags or stop strings are possible to be constrained. Otherwise, they are definitely accepted. This PR takes advantage of it, and brings more efficiency improvement.

[Optim] Optimize the efficiency of TagDispatch expressions.

---

cpp/earley_parser.cc
cpp/grammar_compiler.cc
cpp/grammar_functor.cc
cpp/grammar_functor.h
cpp/grammar_impl.h
cpp/nanobind/nanobind.cc
cpp/support/json_serializer.h
python/xgrammar/testing.py
tests/cpp/test_fsm_builder.cc
tests/python/test_grammar_matcher_structural_tag.py
tests/python/test_grammar_parser.py
tests/python/test_json_schema_converter.py
tests/python/test_serialization.py
tests/python/test_structural_tag_converter.py

This is a rebased version of #383.
This PR refactors the pipeline. The functors in `grammar_functor` are divided into three types:
- `grammar_normalizer`: When a grammar is constructed, they should be called immediately.
- `grammar_optimizer`: When a grammar is going to be compiled, they will be called.
- `grammar_constructor`: They are used to construct a new grammar, like constructing the union of two grammars.

[Refac] Refactor the pipeline.

---

python/xgrammar/tokenizer_info.py
tests/python/test_tokenizer_info.py

As reported in #444, this PR supported openGPT-x's tokenizer.
openGPT-x's tokenizer is a sentence piece tokenizer, but it uses a unusual method to intialize its SentencePieceProcessor: `self.tok`. This PR supports this situation.

[Feature] support openGPT-x tokenizer.

---

cpp/grammar_matcher.cc
cpp/nanobind/nanobind.cc
docs/xgrammar_features/runtime_safeguards.md
include/xgrammar/matcher.h
python/xgrammar/__init__.py
python/xgrammar/matcher.py
tests/python/test_grammar_matcher_basic.py

This PR provides a series of methods to batched fill next token mask and batched accept string/token for `GrammarMatcher`. In general, there are three new methods:
- `batch_fill_next_token_bitmask(matchers: List["GrammarMatcher"], bitmask: ArrayLike, index: int = 0, max_threads: int = 16, debug_print: bool = False)`
- `batch_accept_string(matchers: List["GrammarMatcher"], strings: List[str], debug_print: bool = False)`
- `batch_accept_token(matchers: List["GrammarMatcher"], tokens: List[int], debug_print: bool = False)`
These methods allow users to fill multiple `GrammarMatcher`s' token masks in a batch, and reduce the overhead of the transversion between cpp and python.

[Feature] Provide batched fill next token mask and batched accept string/token methods.

---

cpp/grammar_builder.h

This PR fixes the function `AddRule`. In the original version, `rules` will be uncessarily copied for a lot of times, and this PR fixes it.

[Fix] Fix AddRule.

---

cpp/earley_parser.cc
cpp/earley_parser.h
cpp/grammar_matcher.cc

As reported in #443, it may be hard to understand the prediction and completion relationship in the Earley parser. This PR provides more detailed informations for developers and users to check the states in the Earley parser. 
This is the comparison between the main branch and this PR(left: this PR, right: main branch).

[Feature] Provide more detailed debug print information in AcceptString and AcceptToken.
