mlc-ai/xgrammar

cpp/grammar_matcher_preproc.h, cpp/pybind/pybind.cc, cpp/support/thread_safe_cache.h, python/xgrammar/xgrammar.py, tests/python/test_grammar_compiler.py
This PR supports a thread-safe cache for the CachedGrammarCompiler. This enables fast multi-thread processing of grammar.
=> [Feature] Thread-safe cache

cpp/support/thread_safe_cache.h
This PR removes useless lines for #28
=> [Fix] Fix #28

CMakeLists.txt, cpp/grammar_matcher.cc, cpp/json_schema_converter.cc, cpp/pybind/pybind.cc, cpp/pybind/python_methods.cc, cpp/pybind/python_methods.h, cpp/support/dynamic_bitset.h, web/src/xgrammar.ts, web/src/xgrammar_binding.cc
This PR fixes errors and bugs found in integration with MLC-LLM.
=> [Fix] Fix error in integration with MLC-LLM

README.md, cpp/kernels/apply_token_mask_inplace.cu
This PR adds a draft document containing compile guidance and usage.
This PR also fixes a bug in ApplyTokenBitmaskInplaceKernel.
=> [Doc] Add usage docs

README.md, cpp/grammar_cached_compiler.h, cpp/grammar_data_structure.h, cpp/grammar_functor.cc, cpp/grammar_functor.h, cpp/grammar_matcher.cc, cpp/grammar_matcher_base.h, cpp/pybind/pybind.cc, cpp/support/thread_pool.h, cpp/tokenizer.cc, include/xgrammar/xgrammar.h, python/xgrammar/xgrammar.py
This PR supports multi-thread grammar complication, therefore significantly speeds up the preprocessing stage. 
APIs:
```
compiler = CachedGrammarCompiler(tokenizer_info, max_threads)
compiled_grammar = CompiledGrammar(grammar, tokenizer_info, max_threads)
```
=> [Feature] Multi-thread Grammar Compilation

README.md, scripts/local_deploy_site.sh, site/.gitignore, site/CNAME, site/Gemfile, site/_config.yml, site/index.md
This PR sets up the `site` directory and the landing page.
=> [Docs] `site` and landing page setup

python/requirements.txt, scripts/build_xgrammar_wheel_manylinux.sh, scripts/docker/bash.sh, scripts/sync_package.py, version.py
This PR sets up the CD workflow for Python packaging.
=> [Package] Setup Python packaging

.github/workflows/wheel_manylinux.yaml, scripts/sync_package.py
This PR adds the CD workflow file, which will be triggered when a new tag is pushed.
=> [Package] Add GitHub action package build workflow

.github/workflows/wheel_manylinux.yaml
This PR switches the upload destination from testpypi to pypi.
=> [Package] Build and upload to PyPI

benchmark/README.md, benchmark/bench_grammar_compile_mask_gen.py, python/xgrammar/xgrammar.py
This PR adds benchmark scripts for JSON schema generation. For results see `benchmark/README.md`.
=> [Bench] Add engine efficiency benchmark

README.md, docs/start/install.rst, python/setup.py, python/xgrammar/cuda/apply_token_mask_inplace.py, python/xgrammar/support/__init__.py, python/xgrammar/support/logging.py
This PR updates the JIT-compilation related docs and error reporting.
Specifically,
* The installation doc page is updated with the pip install instruction and the CUDA dependency installation instruction.
* CUDA home detection is added.
* More detailed error messages are added for JIT compilation when the CUDA dependency is not properly installed.
=> [Python] Detailed info for JIT compilation

benchmark/README.md
This PR removes the results because they are generally subject to change.
=> [Bench] Update benchmark readme

web/example/package.json, web/package-lock.json
This PR updates the package-lock.json and releases web-xgrammar npm package version 0.1.0
=> [Package][Web] Publish web-xgrammar npm version 0.1.0

docs/api/python/index.rst, docs/conf.py, docs/index.rst, docs/requirements.txt, python/xgrammar/base.py, python/xgrammar/compiler.py
This PR sets up the python api reference.
=> [DOCS] Add API reference

.github/workflows/documentation.yaml, docs/requirements.txt
This PR adds the missing dependency for API reference in documentation.
=> [Docs] Add missing dependency for API reference

python/xgrammar/matcher.py
This PR clarifies the behavior of apply_bitmask_inplace
=> [DOCS] Clarify behavior of apply_bitmask_inplace

docs/how_to/engine_integration.rst, docs/how_to/portable_api.rst, docs/index.rst
=> [Docs] Add portable API

docs/how_to/ebnf_guided_generation.rst, docs/how_to/json_generation.rst
Trivial fixes. All codes snippets tested.
=> [Docs] All code snippet tested

python/xgrammar/matcher.py
This PR fixes the problem in fill_next_token_bitmask related to C++ binding.
=> [Fix] Fix C++ binding for fill_next_token_bitmask

cpp/json_schema_converter.cc
This PR provides a verbose option for json_schema_converter.
=> [Feat] Add a verbose option for json_schema_converter

cpp/json_schema_converter.cc, python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.py
This PR fixes the cuda compilation error.
=> [Fix] Fix CUDA compilation error

scripts/release_new_version.sh
This PR adds a release_new_version.sh to help release new versions.
=> [Script] Add release_new_version.sh

scripts/release_new_version.sh
This PR updates release_new_version.sh.
=> [Script] Update release_new_version.sh

tests/python/test_json_schema_converter.py
This PR fixes JSON schema tests caused by the change on the json schema converter in #98.
=> [Fix] Fix JSON Schema tests 

docs/start/install.rst
This PR updates the installation document to add instruction to setup precommit hooks.
=> [Doc] Update installation doc

scripts/release_new_version.sh
This PR updates release_new_version.sh to check wrong usage, and provide an execution permission to it.
=> [Package] Update release_new_version.sh

docs/requirements.txt
This PR fixes the dependencies for docs to prevent building failure.
=> [Fix] Fix doc dependencies

cpp/grammar.cc, cpp/grammar_builder.h, cpp/grammar_functor.cc, cpp/grammar_functor.h, cpp/pybind/pybind.cc, include/xgrammar/grammar.h, python/xgrammar/grammar.py, python/xgrammar/testing.py, tests/python/test_grammar_union_concat.py
This PR provides APIs for finding the concatenation and union for grammars. The concat API is provided as a static function of Grammar, while union is a private function in testing. The latter will be moved out later with more tests.
=> [Feature] Grammar concat and union

python/xgrammar/version.py
=> Bump to 0.1.10

cpp/support/logging.h, include/xgrammar/compiler.h
This PR removes the debug checking in #162.
=> [Fix] Fix #162

cpp/support/dynamic_bitset.h, cpp/support/utils.h
This PR fixes the usage of popcount on windows using `__popcnt`.
=> [Fix] Fix popcount for windows

.pre-commit-config.yaml
This PR adds a slide introducing XGrammar
=> [Resource] Add XGrammar Slides

.pre-commit-config.yaml
This PR sets up yamlfmt in pre-commit config to automatically format updated yaml files.
=> [Format] Setup yamlfmt

README.md
=> [Doc] add pypi version in README

cpp/grammar_compiler.cc, cpp/pybind/pybind.cc, include/xgrammar/compiler.h, python/xgrammar/compiler.py, tests/python/test_grammar_matcher_regex.py, tests/python/test_grammar_matcher_tag_dispatch.py
This PR supports regex for grammar compiler, finalizing the support for regex in xgrammar.
=> [Feature] Support Regex for GrammarCompiler

README.md
This PR adds the news section in readme.md.
=> [Docs] Add news section

.pre-commit-config.yaml, pyproject.toml
This PR adds the toml formatter pre-commit hook.
=> [Maintain] Add toml formatter

.github/workflows/wheel_manylinux.yaml, scripts/build_xgrammar_wheel_manylinux.sh
This PR updates the image for linux packaging to support python 3.13.
=> [Fix] Update packaging image

cpp/ebnf_script_creator.cc, cpp/ebnf_script_creator.h, cpp/json_schema_converter.cc, python/xgrammar/kernels/apply_token_bitmask_inplace_cuda.cu, tests/python/test_json_schema_converter.py
This PR supports the self recursion in json schema. 
It also fixes #207, because previously this would lead to an infinite recursion in the json schema converter. Now the main branch will not segfault on maskbench.
=> [Feature] Support self-recursion in json schema reference

python/xgrammar/matcher.py
This PR postpones the cuda initialization (torch.cuda.is_available()) to the calling site to avoid the `re-initializing CUDA in forked subprocess` error
=> [Fix] Postpone cuda import to the calling site

pyproject.toml
This pr adds dependency for ninja for torch extension
=> Add dependency for ninja

.github/workflows/build_and_release.yaml, .github/workflows/close_issues.yaml, .github/workflows/documentation.yaml, .github/workflows/unit_test.yaml, pyproject.toml, scripts/lint.sh, tests/cpp/test_thread_pool.cc, tests/python/test_grammar_matcher_json.py, tests/python/test_grammar_matcher_json_schema.py
This PR mainly updates the CI:
- Integrate format check in unit_test.yaml.
- Add a yaml to close stale issues.
- Add the check in document.yaml to avoid the annoying notifications.
- Fix some minor format problems.
=> [Feature] Add CI to close inactive issues and check formats.

.github/workflows/close_issues.yaml, .yamlfmt
This PR updates the logics for staling and closing PRs, extending the stale time and avoiding important issues to be closed.
=> Update logics for stale issues

pyproject.toml, tests/python/test_json_schema_converter.py
Since Annotated is a new feature in python3.9, I removed them to ensure the tests can run with python3.8.
=> [Test]Modify the tests to support python3.8.

.github/workflows/tmate.yaml
This PR sets up tmate to help debugging CI.
=> Setup tmate

tests/python/test_grammar_compiler.py
=> [Minor] Fix missing mark hf_token_required

cpp/nanobind/nanobind.cc
This PR releases GIL for key methods to allow parallelization in integrations.
=> Release GIL for key methods

.github/workflows/benchmark.yaml
At present, bennchmark.yaml will automatically run every day, and often annoy me with a "Run failed". Adding a check may be better.
=> [Ci] Add a check in benchmark.yaml.

python/xgrammar/version.py
=> Bump to v0.1.19

CMakeLists.txt, cpp/compiled_grammar_data_structure.h, cpp/grammar_builder.h, cpp/grammar_functor.cc, cpp/grammar_functor.h, cpp/grammar_parser.cc, cpp/grammar_parser.h, cpp/grammar_serializer.cc, cpp/regex_converter.cc, cpp/support/encoding.cc, cpp/support/encoding.h, cpp/support/thread_safe_cache.h, include/xgrammar/object.h, pyproject.toml, tests/cpp/test_parser.cc, tests/cpp/test_utils.h, tests/python/test_grammar_matcher_structural_tag.py, tests/python/test_grammar_parser.py, tests/python/test_regex_converter.py
This PR refactors the EBNF parser with a lexer-parser architecture. It also supports defining macros for future extensions.
=> [Refactor] Refactor Parser

cpp/fsm.cc, cpp/fsm.h, cpp/fsm_builder.cc, cpp/fsm_builder.h, cpp/grammar_compiler.cc, cpp/grammar_matcher_base.cc, cpp/support/csr_array.h, cpp/support/union_find_set.h, cpp/support/utils.h, include/xgrammar/object.h, tests/cpp/test_fsm.cc, tests/python/test_grammar_matcher_structural_tag.py
This PR refactors the FSM library for better clarity and efficiency.
=> [Refactor] Refactor FSM Library

cpp/grammar_matcher_base.cc, cpp/persistent_stack.h, cpp/support/logging.h
This PR fixed the printing of stackelement.
=> refactor: fix printing stackelement

docs/api/python/bitmask_ops.rst, docs/api/python/index.rst, docs/api/python/recursion_depth.rst, docs/api/python/structural_tag_item.rst, docs/conf.py, docs/requirements.txt, python/xgrammar/grammar.py, python/xgrammar/matcher.py
This PR further refactors the docs by grouping global methods.
=> Further update docs

docs/Makefile
https://github.com/mlc-ai/xgrammar/issues/342#issuecomment-3016849155
=> Use python3 to build docs

README.md, todo
=> [docs] Further fix docs

python/xgrammar/version.py
=> Bump to v0.1.20

cpp/support/thread_safe_cache.h
1. Fix the bug when an exception happens in creating an entry
2. Fix missing clear map when LRU is not enabled (unlimited case)
When `std::packaged_task` gets an exception inside the task, the associated `std::shared_future` will rethrow the exception on calling `get()` method. When this happens in LRU operations, this will lead to underlying cache inconsistency.
We fix this by catching all the possible exceptions (hopefully) when `get()` is called.
=> Fix: fix wrong LRU cache implementation

python/xgrammar/version.py
=> Bump to v0.1.21

python/xgrammar/matcher.py
=> Fix docs for GrammarMatcher.__init__

docs/api/python/config.rst, docs/api/python/exception.rst, docs/api/python/index.rst, docs/index.rst, docs/xgrammar_features/serialization.md, python/xgrammar/compiler.py, python/xgrammar/exception.py, python/xgrammar/grammar.py, python/xgrammar/tokenizer_info.py
This PR adds docs for serialization and fixes the problem in it.
=> Fix document error and add docs for serialization

pyproject.toml
=> Bump to v0.1.24

python/xgrammar/testing.py, tests/python/test_token_bitmask_operations.py
This PR renames two functions to expose them.
=> [Format] Rename two testing functions to expose them.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This PR provides issue templates for bug reports and feature requests. The templates can improve the efficiency to resolve the problem.
=> [Doc] Add issue templates.

pyproject.toml
=> Bump to v0.1.25
